version: '3.5'
services:
  kidsaccounts:
    build:
      context: .
    container_name: kidsaccounts
    restart: unless-stopped
    environment:
      VELVET_PW: 'VELVETPWVAL'
      MICHAEL_PW: 'MICHAELPWVAL'
      AUTH_SECRET: 'AUTHSECRETVAL'
      PG_CONNECTION_STRING: 'PGCONNSTRINGVAL'
      NODE_ENV: 'production'
    ports:
      - 3000:3000